### ISSUE TITLE
Is this just my impatience or shall I keep working on it?

### ISSUE THREAD

**Issue by Vision-Live** [themefisher/kross-jekyll#12]
https://vision-live.github.io/FXRaven/

Here I have tried to load up the content with no additions and so I'm guessing it's me being impatient but I really want to start perfecting it.

It makes more sense to perfect it through local host as stated but I just wanted to check. Also as I'm a beginner is this a problem with the CSS being processed? Brilliant job btw!

**Comment by somratpro** [comment]
Hello @Vision-Live 

Thank you for choosing this template, you might need to provide `baseurl` in your `_config.yml` file to render css and images correctly, your baseurl sould be `FXRaven/`

**Comment by Vision-Live** [comment]
I'm very pleased with the results so far! Keep up the good work! I'll close now
