### ISSUE TITLE
Trailing slashes

### ISSUE THREAD

**Issue by jcuenod** [themefisher/kross-jekyll#6]
When running locally, everything works fine but on `gh-pages` the trailing slashes in `_data/settings.yml` appear to break the routing so that while the framework of the page loads it displays a 404 (if the trailing slashes are removed, it works).

https://github.com/themefisher/kross-jekyll/blob/master/_data/settings.yml#L13-L17

**Comment by developer-evan** [comment]
Hey @jcuenod 

thanks for your concern, i made the changes as you told. can you check it out?

also if you like this theme, please consider to giving a star to the repository.

**Comment by jcuenod** [comment]
It looks like your last commit implements this change, yes. It works for me...
I had already starred this repo before I submitted this issue.
