### ISSUE TITLE
Invalid CSS after "...ort 'variables'": expected "{", was ";" on line 15 of /xxxx/assets/scss/style.scss

### ISSUE THREAD

**Issue by jordanurbs** [themefisher/kross-jekyll#7]
I get this error after building with some new CSS changes. I think its from _variables.scss but for the life of me can't figure out what. I have even reverted back to original versions, and re-made my changes, with no luck.

Locally, sometimes I'll stop the jekyll build and build again, or refresh then page in my browser, and the error will disappear. It's quite odd.

**Comment by developer-evan** [comment]
hey @jordanurbs 

Is this still happening with you? I have checked it on localhost and everything works fine. I also recommend you to update your ruby gems and jekyll to the latest version. thanks for being with us.

**Comment by jordanurbs** [comment]
@developer-evan yes it still happens. Locally it builds correctly 50% of the time. Remotely it doesn't build correctly. 

To resolve, I replaced all sass variables with my desired colors, converted all sass to css, and made a static css asset.

Not clean but worth it--I love the theme!

**Comment by jcuenod** [comment]
Just fyi, mine is building remotely without a problem.

**Comment by developer-evan** [comment]
@jordanurbs 

This is only happening with you, I am not sure why...
Everyone else, using this theme withut any issue like this. If it does not happend with me, I can't fix it actually. So if you are using this theme with css, and didn't fetching any issue, then you should use it like this. I am going to close this issue, thanks for being with themefisher.
